### ISSUE TITLE
[LOAD-TESTING] Load Testing Pending Tasks

### ISSUE THREAD

**Issue by fkrause98** [lambdaclass/mirra_backend#514]
## 🚧 Load Testing
These are the pending tasks related to load testing
- [x]  remove dirty schedulers from nif’s code > [PR](https://github.com/lambdaclass/lambda_backend_game_engine/pull/40)(https://github.com/lambdaclass/lambda_backend_game_engine/pull/40)
    - [x]  Do a UX test before/after merging.
    - [ ]  Re-do the fprof file and check if we still have the undefined value on the execution tree.
- [ ]  Set up flamegraphs for Elixir (#1152):
     - First option: [Dockyard article](https://dockyard.com/blog/2022/02/22/profiling-elixir-applications-with-flame-graphs-and-flame-on)(to research).
     - Second Option: [Incendium](https://github.com/tmbb/incendium) (to research).

- [ ] lambdaclass/mirra_backend#509
- [x]  Improve load testing api, eg: Do not use milliseconds as time unit.
- [x]  Improve server state observability (Amin is on this):
    - We’d like to check how many players there are on a given game instance.
    - Maybe add some endpoints/gen server calls to ask about the state of the game instance?.
- [ ]  Extend parameter possibilites for load testing, parametrize what we can ONLY for load testing environments, accessing this should not be possible on dev/prod.
I think we can limit this to be about the amount of players and games.
- [x]  Do load tests from a bare-metal server, as to avoid consumer network
and hardware limitations.
- [x]  Improve load testing / benchmarking (#1153).
- [ ]  After doing a run of proper load tests, do a newer round of load tests but with bots inside games (maybe this could be another parameter /  a new api endpoint) and also compare results when having 10 players per game vs 30 players per game
- [ ]  Automatize the steps below as scripts, if we can.
- [ ]  Test different BEAM flags to see how the server reacts:
- +scl true|false.
- +sfwi Interval.
Reference:** https://www.erlang.org/doc/man/erl.html. 
Anything from here could also be tested to see how the server behaves.
- [ ]  Add Github action to deploy server and load-testing client.
- [ ] lambdaclass/mirra_backend#510
- [ ] Time each nif
